module.exports = {
  alpha: 'El campo :attribute debe contener solo caracteres',
  alpha_numeric: 'El campo :attribute debe contener solo númeeros y caracteres',
  array: 'El campo :attribute debe ser un array',
  between: 'El campo :attribute debe estar entre :min y :max',
  boolean: 'El campo :attribute debe ser un booleano',
  date: 'El campo :attribute debe ser una fecha válida',
  email: 'El campo :attribute debe ser una dirección de email',
  in: 'El campo :attribute debe ser uno de los siguientes :list',
  numeric: 'El campo :attribute debe ser numerico',
  max: 'El campo :attribute debe ser menor o igual que :max',
  min: 'El campo :attribute debe ser mayor o igual que :min',
  not_in: 'El campo :attribute no debe ser uno de los siguientes :list',
  required: 'El campo :attribute debe estar presente y no nulo',
  size: 'El tamaño del campo :attribute debe ser de :size',
  string: 'El campo :attribute debe ser texto',
};